import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles/tokens.css'
import './styles/base.css'
import './styles/screens.css'
import './styles/nav.css'

// ── Service Worker registration with forced auto-update ────────────────────
// The default registerSW.js generated by vite-plugin-pwa 0.20.5 only calls
// navigator.serviceWorker.register() — it never calls reg.update() or
// listens for controllerchange. This means when a new deployment changes
// CSS/JS hashes, the old SW keeps serving stale HTML that references old
// asset files. Those old files no longer exist on Vercel, and the SPA
// catch-all rewrite serves index.html (HTML) instead of the CSS file.
// The browser then receives HTML where CSS is expected, and no styles apply.
//
// This fix:
// 1. Calls reg.update() on every page load to check for a new SW immediately.
// 2. Listens for controllerchange and reloads the page so the new SW serves
//    the new HTML (which references the new, existing CSS file).
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js', { scope: '/' })
      .then((reg) => {
        // Force-check for SW updates on every navigation.
        void reg.update()
      })
      .catch((err) => console.warn('[sw] registration failed:', err))

    // When a new SW takes control (skipWaiting + clientsClaim), reload
    // the page so the user gets the new HTML with the new asset hashes.
    let refreshing = false
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      if (refreshing) return
      refreshing = true
      window.location.reload()
    })
  })
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
